{
    "name": "Custom Chart of Accounts",
    "version": "1.0",
    "depends": ["account"],
    "author": "Generated by ChatGPT",
    "category": "Accounting",
    "summary": "Custom chart of accounts per selected companies.",
    "description": "Create and sync custom account entries for multiple companies.",
    "depends": ['tms_settings', "l10n_generic_coa"],

    "data": [
        "security/ir.model.access.csv",
        "views/custom_account_views.xml"
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    'post_init_hook': 'post_init_hook',
}
